### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by pradeepkc11** [ControlNet/LAV-DF#13]
File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 401, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 155, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 395, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = accelerator_cls.parse_devices(self._devices_flag)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/accelerators/cuda.py", line 82, in parse_devices
    return _parse_gpu_ids(devices, include_cuda=True)
  File "/home/pradeep/.local/lib/python3.10/site-packages/lightning_fabric/utilities/device_parser.py", line 77, in _parse_gpu_ids
    _check_data_type(gpus)
  File "/home/pradeep/.local/lib/python3.10/site-packages/lightning_fabric/utilities/device_parser.py", line 198, in _check_data_type
    raise TypeError(f"{msg} None")
TypeError: Device IDs (GPU/TPU) must be an int, a string, a sequence of ints, but you passed None

can any explain me how to solve this error

**Comment by ControlNet** [comment]
Could you please list the python version, lightning version and the args you used for running the scripts?

**Comment by pradeepkc11** [comment]
absl-py==2.0.0
aicsimageio==4.14.0
aiobotocore==2.5.4
aiohttp==3.8.6
aioitertools==0.11.0
aiosignal==1.3.1
albumentations==1.3.1
annotated-types==0.6.0
asciitree==0.3.3
astunparse==1.6.3
async-timeout==4.0.3
attrs==23.1.0
audioread==3.0.1
av==11.0.0
beautifulsoup4==4.12.2
blinker==1.4
blis==0.7.11
botocore==1.31.17
bottle==0.12.25
bottle-websocket==0.2.9
Brotli==1.1.0
bs4==0.0.1
cachetools==5.3.2
catalogue==2.0.10
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
chromedriver-binary==74.0.3729.6.0
click==8.1.7
cloudpathlib==0.16.0
cloudpickle==3.0.0
cmake==3.27.7
colorama==0.4.6
command-not-found==0.3
confection==0.1.3
contourpy==1.2.0
cryptography==3.4.8
cycler==0.12.1
cymem==2.0.8
dask==2023.10.1
dbus-python==1.2.18
decorator==5.1.1
densenet-pytorch==0.2.0
distributed==2023.10.1
distro==1.7.0
distro-info===1.1build1
dlib==19.24.2
Eel==0.16.0
efficientnet-pytorch==0.7.1
einops==0.7.0
elementpath==4.1.5
et-xmlfile==1.1.0
exceptiongroup==1.1.3
fasteners==0.19
filelock==3.13.1
flatbuffers==23.5.26
fonttools==4.44.0
frozenlist==1.4.0
fsspec==2023.6.0
future==0.18.3
gast==0.5.4
gdown==4.7.1
gevent==23.9.1
gevent-websocket==0.10.1
google==3.0.0
google-auth==2.23.4
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
greenlet==3.0.1
grpcio==1.59.2
h11==0.14.0
h5py==3.10.0
httplib2==0.20.2
huggingface-hub==0.18.0
idna==3.4
imagecodecs==2023.9.18
imageio==2.31.6
importlib-metadata==6.8.0
imutils==0.5.4
jeepney==0.7.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
keras==2.14.0
keyring==23.5.0
kiwisolver==1.4.5
langcodes==3.3.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.3
libclang==16.0.6
librosa==0.10.1
lightning-utilities==0.10.0
llvmlite==0.41.1
locket==1.0.0
lxml==4.9.3
Markdown==3.5.1
MarkupSafe==2.1.3
matplotlib==3.8.1
ml-dtypes==0.2.0
more-itertools==8.10.0
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
munch==4.0.0
murmurhash==1.0.10
mutagen==1.47.0
netifaces==0.11.0
networkx==3.2.1
nltk==3.8.1
numba==0.58.1
numcodecs==0.12.1
numpy==1.26.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.0
ome-types==0.4.2
ome-zarr==0.8.2
opencv-python==4.8.1.78
opencv-python-headless==4.8.1.78
openpyxl==3.1.2
opt-einsum==3.3.0
outcome==1.3.0.post0
packaging==23.2
pafy==0.5.5
pandas==2.1.2
partd==1.4.1
piexif==1.1.3
Pillow==10.0.1
platformdirs==3.11.0
pooch==1.8.0
preshed==3.0.9
pretrainedmodels==0.7.4
protobuf==4.23.4
psutil==5.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pycryptodomex==3.19.0
pydantic==2.4.2
pydantic_core==2.10.1
pyDeprecate==0.3.2
pydub==0.25.1
PyGObject==3.42.1
PyJWT==2.3.0
pyparsing==2.4.7
PySocks==1.7.1
pyTelegramBotAPI==4.14.0
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.2
pytorch-lightning @ file:///home/pradeep/pytorch_lightning-1.7.7-py3-none-any.whl#sha256=4438b8284d7f7fdb06cf3566a7b5b6f102ac8971cf7bb6d3f1b1de64628241f3
pytz==2023.3.post1
PyYAML==6.0.1
qudida==0.0.4
regex==2023.10.3
requests==2.31.0
requests-oauthlib==1.3.1
resource-backed-dask-array==0.1.0
rpycolors==0.0.5
rsa==4.9
s3fs==2023.6.0
safetensors==0.4.0
scikit-image==0.22.0
scikit-learn==1.3.2
scipy==1.11.3
searchtweets==1.7.6
SecretStorage==3.3.1
segmentation-models-pytorch==0.3.3
selenium==4.15.2
six==1.16.0
smart-open==6.4.0
sniffio==1.3.0
snscrape==0.7.0.20230622
sortedcontainers==2.4.0
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.7
spacy==3.7.2
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.4.8
sympy==1.12
systemd-python==234
tblib==3.0.0
telebot==0.0.5
telegram==0.0.1
tensorboard==2.14.1
tensorboard-data-server==0.7.2
tensorflow==2.14.0
tensorflow-estimator==2.14.0
tensorflow-hub==0.15.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.3.0
textblob==0.17.1
thinc==8.2.1
threadpoolctl==3.2.0
tifffile==2023.2.28
timm==0.9.2
tk==0.1.0
toml==0.10.2
toolz==0.12.0
torch==2.1.1
torchaudio==2.1.1
torchmetrics==0.11.4
torchvision==0.16.0
tornado==6.3.3
tqdm==4.66.1
trio==0.23.1
trio-websocket==0.11.1
triton==2.1.0
tweepy==4.14.0
tweet-parser==1.13.2
tweety==0.1.6
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
ubuntu-advantage-tools==8001
ufw==0.36.1
unattended-upgrades==0.1
UNKNOWN @ git+https://github.com/JustAnotherArchivist/snscrape.git@614d4c2029a62d348ca56598f87c425966aaec66
urllib3==1.26.18
vaderSentiment==3.3.2
wadllib==1.3.6
wasabi==1.1.2
weasel==0.3.4
websockets==12.0
Werkzeug==3.0.1
whichcraft==0.6.1
wrapt==1.14.1
wsproto==1.2.0
xarray==2023.10.1
xmlschema==2.5.0
xsdata==23.8
yarl==1.9.2
youtube-dl==2021.12.17
youtube-extract==1.4.0
yt-dlp==2023.10.13
zarr==2.15.0
zict==3.0.0
zipp==1.0.0
zope.event==5.0
zope.interface==6.1

**Comment by pradeepkc11** [comment]
python3 evaluate.py --config /home/pradeep/LAV-DF/config/batfd_plus_default.toml --data_root /home/pradeep/LAV-DF/dataset --checkpoint /home/pradeep/LAV-DF/batfd_plus_default.ckpt --batch_size 1 --num_workers 4

**Comment by pradeepkc11** [comment]
I used above args to check if it works or not

**Comment by ControlNet** [comment]
Could you please try adding `gpus 1`

**Comment by pradeepkc11** [comment]
I set the gpus as 1 then i am getting this error

Traceback (most recent call last):
  File "/home/pradeep/LAV-DF/evaluate.py", line 131, in <module>
    evaluate_lavdf(config, args)
  File "/home/pradeep/LAV-DF/evaluate.py", line 81, in evaluate_lavdf
    inference_batfd(model_name, model, dm, config["max_duration"], model_type, args.modalities, args.gpus)
  File "/home/pradeep/LAV-DF/inference.py", line 147, in inference_batfd
    trainer.predict(model, dm.test_dataloader())
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in predict
    return self._call_and_handle_interrupt(
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1251, in _run_stage
    return self._run_predict()
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_predict
    return self.predict_loop.run()
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 102, in advance
    dl_predictions, dl_batch_indices = self.epoch_loop.run(
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 101, in advance
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 137, in _predict_step
    self.trainer._call_callback_hooks("on_predict_batch_end", predictions, batch, batch_idx, dataloader_idx)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1597, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/pradeep/LAV-DF/inference.py", line 74, in on_predict_batch_end
    self.gen_df_for_batfd_plus(fusion_bm_map[i], nullable_index(fusion_start, i), nullable_index(fusion_end, i),
  File "/home/pradeep/LAV-DF/inference.py", line 114, in gen_df_for_batfd_plus
    df = df[(df.duration > 0) & (df.end <= n_frames)]
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/arraylike.py", line 52, in __le__
    return self._cmp_method(other, operator.le)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/series.py", line 5799, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 349, in comparison_op
    res_values = _na_arithmetic_op(lvalues, rvalues, op, is_cmp=True)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/pradeep/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'Tensor'

**Comment by ControlNet** [comment]
Thanks. Now I have reproduce the problem, and fixed in https://github.com/ControlNet/LAV-DF/commit/fa0ace9ddcce8351516ca3ec13590f73a6f102f2. Hope this can solve your problem.

**Comment by pradeepkc11** [comment]
Thanks it's solved the problem.
