### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by mowen9** [ControlNet/LAV-DF#14]
When I run the following command:
            python evaluate.py \
              --config ./config/batfd_default.toml \
              --data_root $DATASET_PATH \
              --checkpoint ./ckpt/batfd_default/last.ckpt 

I meet this error:

Load 113541 data in train.
Load 0 data in dev.
Load 4150 data in test.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/opt/data/private/code/DFD/3.LAV-DF-master/evaluate.py", line 128, in <module>
    evaluate_lavdf(config, args)
  File "/opt/data/private/code/DFD/3.LAV-DF-master/evaluate.py", line 78, in evaluate_lavdf
    inference_batfd(model_name, model, dm, config["max_duration"], model_type, args.modalities, args.gpus)
  File "/opt/data/private/code/DFD/3.LAV-DF-master/inference.py", line 147, in inference_batfd
    trainer.predict(model, dm.test_dataloader())
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in predict
    return self._call_and_handle_interrupt(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 107, in launch
    mp.start_processes(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/root/miniconda3/envs/py3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_get_Conv.<locals>._ConvNd'

Could you help me solve this error?

**Comment by ControlNet** [comment]
Could you please share your checkpoint with me, so I can have a look? You can send it to my email.

**Comment by mowen9** [comment]
> Could you please share your checkpoint with me, so I can have a look? You can send it to my email.

Thanks for your reply. I have solved this error. 

I have another question. I would like to request if it would be possible for you to provide the code for calculating AUC.

**Comment by ControlNet** [comment]
Answered in https://github.com/ControlNet/LAV-DF/issues/16.

**Comment by Kathy1214** [comment]
> > Could you please share your checkpoint with me, so I can have a look? You can send it to my email.
  > 
  > Thanks for your reply. I have solved this error.
  > 
  > I have another question. I would like to request if it would be possible for you to provide the code for calculating AUC.
I meet the same problem AttributeError: Can't pickle local object '_get_Conv.._ConvNd' Could you tell me how did you solve this error?

**Comment by Kathy1214** [comment]
> > Could you please share your checkpoint with me, so I can have a look? You can send it to my email.
> 
> Thanks for your reply. I have solved this error.
> 
> I have another question. I would like to request if it would be possible for you to provide the code for calculating AUC.

I meet the same problem AttributeError: Can't pickle local object '_get_Conv.._ConvNd' Could you tell me how did you solve this error?

**Comment by ControlNet** [comment]
> > > Could you please share your checkpoint with me, so I can have a look? You can send it to my email.
> > 
> > 
> > Thanks for your reply. I have solved this error.
> > I have another question. I would like to request if it would be possible for you to provide the code for calculating AUC.
> 
> I meet the same problem AttributeError: Can't pickle local object '_get_Conv.._ConvNd' Could you tell me how did you solve this error?

@Kathy1214 , I think now it is resolved in https://github.com/ControlNet/LAV-DF/commit/c4b4d32fbd6895988a7e62632fe1985fcfec92f9
